server:
  port: 8080

spring:
  application:
    name: coffeeshop
  datasource:
    url: jdbc:postgresql://<host>:<port>/<database>
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev


logging:
  level:
    root: info
    com.example.myapp: debug

app:
  message : Hi There Configuration
    
